package Spring2019_02;



 
import java.util.List;
/*
 * DO NOT EDIT THIS FILE
 */
public interface ICourse { 

    void f1(List<Course> a, int st);
   
    public int f2(List<Course> a, double fee);
}
